-- TABLA CATALOGO
INSERT INTO CATALOGO (DESCRIPCION_CATALOGO) VALUES ('Tipo de Persona');
INSERT INTO CATALOGO (DESCRIPCION_CATALOGO) VALUES ('Tipo de Identificación');

-- TABLA DETALLE CATALOGO
-- Tipo de Persona
INSERT INTO DETALLE_CATALOGO (ID_CATALOGO, COD_DETALLE_CATALOGO, DESC_DET_CATALOGO) VALUES (1, '1', 'Natural');
INSERT INTO DETALLE_CATALOGO (ID_CATALOGO, COD_DETALLE_CATALOGO, DESC_DET_CATALOGO) VALUES (1, '2', 'Jurídica');
-- Tipo de Identificación
INSERT INTO DETALLE_CATALOGO (ID_CATALOGO, COD_DETALLE_CATALOGO, DESC_DET_CATALOGO) VALUES (2, '1', 'Cédula');
INSERT INTO DETALLE_CATALOGO (ID_CATALOGO, COD_DETALLE_CATALOGO, DESC_DET_CATALOGO) VALUES (2, '2', 'RUC');
INSERT INTO DETALLE_CATALOGO (ID_CATALOGO, COD_DETALLE_CATALOGO, DESC_DET_CATALOGO) VALUES (2, '3', 'Pasaporte');

--TABLA USUARIO
INSERT INTO USUARIO VALUES (1, 'admin', 'PAUL JIMENEZ','admin', '1719186262', 'A', 'A');
INSERT INTO USUARIO VALUES (2, 'fpozo', 'FRANKLIN POZO','fpozo', '1719186262', 'A', 'A');

-- TABLA DE ROL
INSERT INTO ROL VALUES (1, 1, 'COMERCIAL', 'DEPARTAMENTO COMERCIAL', 'A');

--TABLA MENU

INSERT INTO MENU VALUES (1, NULL, 'Administracion', NULL,'A');
INSERT INTO MENU VALUES (2, 4, 'Ingresar Usuarios', '/pages/usuarios.jsf','A');


INSERT INTO ROL_MENU VALUES (1,1,1);
INSERT INTO ROL_MENU VALUES (2,1,2);